[font]
size = 15
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[window]
decorations = "Buttonless"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[colors]
primary = { background = "#000000", foreground = "#eff6ef" }
