[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
decorations = "Buttonless"
padding = { x = 3, y = 3 }
dynamic_padding = true

[colors]
primary = { background = "#111111", foreground = "#eff6ef" }
